name: CI

on:
  push:
  pull_request:

jobs:
  check-schema-diff:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: test
    steps:
    - uses: actions/checkout@v7
    - run: echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
    - parallel:
      - run: go install github.com/pgplex/pgschema@v1.12.0
      - run: brew install sqlx-cli
      - name: Init Database
        run: |
          psql postgres://postgres:test@localhost:5432/postgres -c 'CREATE DATABASE blobmanager'
          psql postgres://postgres:test@localhost:5432/postgres -c 'CREATE DATABASE blobmanager_plan'
    - run: cd blobmanager && sqlx migrate run
      env:
        DATABASE_URL: postgres://postgres:test@localhost:5432/blobmanager
    - run: cd blobmanager && ./generate_migration.sh current_diff && git diff --exit-code
      env:
        PGPASSWORD: test
        PGDATABASE: blobmanager
        PGSCHEMA_PLAN_PASSWORD: test
        PGSCHEMA_PLAN_DB: blobmanager_plan
